
# Model M keyboard with a (bb) leonardo/"pro micro"
# and a keymap that hard-translates Caps Lock to the Windows Key

TARGET := ps2_modelm_leo_winkey
UNIMAP_ENABLE=yes
KEYMAP=modelm_winkey
CONFIG_H = config_modelm_winkey.h

#attempted fix for chromebook Usage
#BOOTMAGIC_ENABLE=no
#CONSOLE_ENABLE=no
#COMMAND_ENABLE=no

include Makefile.model_m_leo
